version: 2.1

orbs:
  win: circleci/windows@2.4.0

workflows:
  build-and-test-all:
    jobs:
      # CircleCI's current generation of Node images, cimg/node, allow you to leave the
      # patch version unpinned, but require you to specify the minor version.
      - build-test-linux:
          name: Node 16.3
          docker-image: cimg/node:16.15
      - build-test-linux:
          name: Node 14.17
          docker-image: cimg/node:14.19
      - build-test-windows:
          name: Windows

jobs:
  build-test-linux:
    parameters:
      run-lint:
        type: boolean
        default: false
      node-args:
        type: string
        default: 'npm'
      docker-image:
        type: string
    docker:
      - image: <<parameters.docker-image>>
    steps:
      - checkout
      - run: echo "Node version:" `node --version`
      - run: npm install
      - run: npm i --prefix=$HOME/.local @cloudflare/wrangler@1.19.3 -g
      - run: 
          command: <<parameters.node-args>> run test && <<parameters.node-args>> run test:integration
      - when:
          condition: <<parameters.run-lint>>
          steps:
            - run: npm run lint
      - run:
          name: dependency audit
          command: ./scripts/better-audit.sh

  build-test-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: node --version
      - run: npm install
      - run: npm test
