version: 2

repo:
  public: cloudflare-edge-sdk
  private: cloudflare-edge-sdk-private

publications:
  - url: https://www.npmjs.com/package/launchdarkly-cloudflare-edge-sdk
    description: npm

jobs:
  - docker:
      image: node:12-buster
    template:
      name: npm

documentation:
  gitHubPages: true
  title: LaunchDarkly Server-Side Cloudflare Edge SDK

sdk:
  displayName: "Cloudflare"
